### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-svcat-controller-manager-operator#6]
lots of "OpenShiftControllerManager" names in files+functions that i think should be SvCatControllerManager

**Comment by jboyd01** [comment]
Agreed, initially I was thinking I could reuse most of OpenShiftControllerManager objects, Derek pointed out those are supposed to be singleton, I'm working through changing these to use new objects & names.

**Comment by jboyd01** [comment]
fixed by https://github.com/openshift/cluster-svcat-controller-manager-operator/pull/11
